[package]
name = "rpi_to_hosts"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopt = "1.1"
clap = { version = "3.0.1", features = [ "cargo" ] }
